// <auto-generated />
namespace Quiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_101));
        
        string IMigrationMetadata.Id
        {
            get { return "202103041851181_version_1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
